server/config/routes.rb
Rails.application.routes.draw do
  devise_for :receivers
  resources :wishlists

  namespace :api do
    namespace :v1 do
      resources :payments
    end
  end
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

server/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :wishlist
end

server/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :wishlist
end

server/app/models/receiver.rb
class Receiver < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wallet, dependent: :destroy
  has_many :wishlists

  after_create :create_wallet

  def create_wallet
    Wallet.create(amount: 0, receiver_id: self.id)
  end
end

server/app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :receiver
end

server/app/models/wishlist.rb
class Wishlist < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :payments
end

server/app/controllers/api/v1/payments_controller.rb
class Api::V1::PaymentsController < ApplicationController
  URL = "https://checkout-test.adyen.com/v40/payments"
  API_KEY = Rails.application.credentials.api_key

  def create
    checkout_adyen
    render json: { status: Payment.last.status }
  end

  private

  def checkout_adyen
    body = {
      "amount": {
        "currency": "EUR",
        "value": 1000
      },
      "reference": SecureRandom.uuid,
      "paymentMethod": {
        "type": "scheme",
        "number": "4111111111111111",
        "expiryMonth": "10",
        "expiryYear": "2020",
        "holderName": "John Smith",
        "cvc": "737"
      },
      "merchantAccount": Rails.application.credentials.merchant_account
    }

    payment = Payment.create(
      giver_reference: body[:reference],
      giver_email: "alisa@test.com",
      comment: "ADD COMMENT HERE!",
      status: "pending",
      wishlist_id: wishlist.id
    )

    begin
      request = RestClient.post(
        URL,
        body.to_json,
        {
          "X-API-key" => API_KEY,
          "Content-Type" => "application/json"
        }
      )
      response = JSON.parse(request.body)

      payment.update(giver_reference: response["pspReference"], status: "success")

      receiver.wallet.update(amount: payment.amount)
    rescue => error
      payment.update(status: "failed")
      error.response.body
    end
  end

  def wishlist
    @wishlist ||= Wishlist.last
  end

  def receiver
    @receiver ||= Receiver.find(wishlist.receiver_id)
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

server/app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url, notice: 'Wishlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.fetch(:wishlist, {})
    end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/wishlists_helper.rb
module WishlistsHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdyenSmartPresent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

server/app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist, local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

server/app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

server/app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= wishlist.name %></td>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

server/app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path %>

server/app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>